apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: whiteboard-service-access
subjects:
  - kind: ServiceAccount
    name: drprofessorowl
    namespace: default
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io