apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-service-deployment
spec:
  selector:
    matchLabels:
      app:  whiteboard-service-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app:  whiteboard-service-k8s
    spec:
      containers:
        - name: whiteboard-service
          image: whiteboard-service:latest
          ports:
            - containerPort: 8081
          imagePullPolicy: Never

