server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver.default.svc.cluster.local:8761
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: whiteboard-service
          uri: lb://whiteboard-service
          predicates:
            - Path=/whiteboard/**
