spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: whiteboard-route
          uri: ${WHITEBOARD_ROUTE_URI:http://10.104.60.71:8081}
          predicates:
            - Path=/whiteboard/**
