spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: whiteboard-route
          uri: ${WHITEBOARD_ROUTE_URI:whiteboard-service}
          predicates:
            - Path=/whiteboard/**
            - Path=/websocket/**
