server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: whiteboard-service
          uri: http://whiteboard-service:8080/
          predicates:
            - Path=/whiteboard/**