server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    kubernetes:
      discovery:
        enabled: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: whiteboard-service
          uri: lb://whiteboard-service
          predicates:
            - Path=/whiteboard/**
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "info", "health" ]
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG