spring:
  application:
    name: whiteboard-service
server:
     port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka

websocket:
  hostname: 0.0.0.0
  port: 8082
