name: Docker CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Navigate to gateway module directory
        run: cd gateway
      
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build/libs 
  
  build-image:

    runs-on: ubuntu-latest
    needs: build

    steps:
      
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: List directory contents
        run: ls -al

      - name: Build and push Docker image
        run: |
          docker build -t drprofessorowl/gateway:latest -f Dockerfile .
          docker push drprofessorowl/gateway:latest
