name: Docker CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Navigate to gateway module directory
        run: cd gateway
      
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gateway-artifact
          path: build/libs/gateway-0.0.1-SNAPSHOT.jar 
  
  build-image:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: gateway-artifact
          path: gateway
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd gateway
          docker build -t drprofessorowl/gateway:latest -f Dockerfile .
          docker push drprofessorowl/gateway:latest
