name: Whiteboard Pipeline

on:
  push:
    paths: 
      - "whiteboard/**"
      - ".github/workflows/whiteboard-pipeline.yml"

permissions:
  contents: read

env:
  repository: whiteboard

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Execute Gradle build
        run: |
          chmod +x ../gradlew
          ../gradlew :${{ env.repository }}:bootJar

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository }}-artifact
          path: ${{ env.repository }}/build/libs

      - name: Print contents of current directory
        run: ls -al
  
  build-image:

    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ${{ env.repository }}
    
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.repository }}-artifact
          path: ${{ env.repository }}/build/libs

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t drprofessorowl/${{ env.repository }}:latest -f Dockerfile .
          docker push drprofessorowl/${{ env.repository }}:latest
